### ISSUE TITLE
ARTK_Plus.a: file not recognized:

### ISSUE THREAD

**Issue by dibyendu-gh** [karldd/ofxARToolkitPlus#1]
Dear Sir,
I am using ofxARToolkitPlus in ubuntu.. but when i compiling i am getting error .../addons/ofxARToolkitPlus/lib/ARTK_Plus.a: file not recognized: File format not recognized.. 
I think it is due to OS.. 
Can you help me please how can i solve this issue..

regards
deb

**Comment by karldd** [comment]
ARTK_Plus.a is the static library for OSX.
So you do not need that file on Ubuntu. Instead you need to compile your own version for linux.
Please refer to the ARToolkitPlus website for those instructions.

**Comment by dibyendu-gh** [comment]
Thank you sir..for your reply ans suggestion...

I have compiled the ARtoolKitplus in ubuntu and also make a static lib .. Now I am trying to incorporate it in ubunt.... and I am getting following error..
 -L../../../addons/ofxOpenCv/libs/opencv/lib/android/armeabi/    ../../../libs/FreeImage/lib/android/armeabi/libfreeimage.a ../../../libs/freetype/lib/android/armeabi/libfreetype.a ../../../libs/glu/lib/android/armeabi/libGLU.a ../../../libs/tess2/lib/android/armeabi/libtess2.a  ../../../libs/poco/lib/android/armeabi/libPocoNet.a ../../../libs/poco/lib/android/armeabi/libPocoXML.a ../../../libs/poco/lib/android/armeabi/libPocoUtil.a ../../../libs/poco/lib/android/armeabi/libPocoFoundation.a  -L../../../libs/FreeImage/lib/android/armeabi -L../../../libs/freetype/lib/android/armeabi -L../../../libs/glu/lib/android/armeabi -L../../../libs/poco/lib/android/armeabi -L../../../libs/tess2/lib/android/armeabi   -lstdc++ -lsupc++ -lgcc -lz -lGLESv1_CM -lEGL -llog -ldl -lm -lc 
/home/deb/Desktop/Install/Downloads/android-ndk-r6/toolchains/arm-linux-androideabi-4.4.3/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.4.3/../../../../arm-linux-androideabi/bin/ld: warning: libcutils.so, needed by /home/deb/Desktop/Install/Downloads/android-ndk-r6/platforms/android-4/arch-arm/usr/lib/libGLESv1_CM.so, not found (try using -rpath or -rpath-link)
obj/androidDebug/src/main.o: In function `testApp':
/home/deb/Desktop/Install/Downloads/OF_android/apps/androidExamples/androidOpenCVExample/src/testApp.h:28: undefined reference to`ofxARToolkitPlus::ofxARToolkitPlus()'
/home/deb/Desktop/Install/Downloads/OF_android/apps/androidExamples/androidOpenCVExample/src/testApp.h:28: undefined reference to `ofxARToolkitPlus::~ofxARToolkitPlus()'
obj/androidDebug/src/testApp.o: In function`testApp::~testApp()':
testApp.cpp:(.text._ZN7testAppD1Ev[testApp::~testApp()]+0x660): undefined reference to `ofxARToolkitPlus::~ofxARToolkitPlus()'
make[1]: Leaving directory`/home/deb/Desktop/Install/Downloads/OF_android/apps/androidExamples/androidOpenCVExample'
testApp.cpp:(.text._ZN7testAppD1Ev[testApp::~testApp()]+0x684): undefined reference to `ofxARToolkitPlus::~ofxARToolkitPlus()'
collect2: ld returned 1 exit status
make[1]: **\* [obj/androidOpenCVExample] Error 1
make: **\* [AndroidDebug] Error 2

thanks
deb

**Comment by karldd** [comment]
Unfortunately I don't have Ubuntu.
Check/post in the forum here to see if someone can help you:
http://forum.openframeworks.cc/index.php?topic=743.135

Karl
